SMLite related changes

diff --git a/testers/smgr_ci_utils_smlite b/testers/smgr_ci_utils_smlite
--- a/testers/smgr_ci_utils_smlite
+++ b/testers/smgr_ci_utils_smlite
@@ -160,19 +160,48 @@ function provision_using_SMLite() {
         server-manager show cluster | grep id | cut -d : -f2 | sed -e 's/^ \"//' -e 's/\"$//'
     ) ")
     cluster_name=`echo $cluster_name | tr -d '\r'`
-    sshpass -p "c0ntrail123" ssh -t -t -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $API_SERVER_HOST_STRING " (
-        set -e
-        set -x
-        #check provisioing status.
-        /root/check_provision.sh $cluster_name
-        if [ $? == 0 ]
-        then
-            echo "Provisioning of the target/cluster is sucessfull!!!"
-        else
-            echo "Provisioning of the target/cluster failed!!! aborting the process"
-            exit 1
-        fi
-    ) "
+    if [ ${TEST_SETUP} == "SINGLENODE" ]
+    then
+        sshpass -p "c0ntrail123" ssh -t -t -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $API_SERVER_HOST_STRING " (
+            set -e
+            set -x
+            #check provisioing status.
+            /root/check_provision.sh $cluster_name
+            if [ $? == 0 ]
+            then
+                echo "Provisioning of the target/cluster is sucessfull!!!"
+            fi
+        ) "
+        sleep 300
+        sshpass -p "c0ntrail123" ssh -t -t -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $API_SERVER_HOST_STRING " (
+            set -e
+            set -x
+            #check provisioing status.
+            /root/check_provision.sh $cluster_name
+            if [ $? == 0 ]
+            then
+                echo "Provisioning of the target/cluster is sucessfull!!!"
+            else
+                echo "Provisioning of the target/cluster failed!!! aborting the process"
+                exit 1
+            fi
+        ) "
+    else
+        sshpass -p "c0ntrail123" ssh -t -t -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $API_SERVER_HOST_STRING " (
+            set -e
+            set -x
+            #check provisioing status.
+            /root/check_provision.sh $cluster_name
+            if [ $? == 0 ]
+            then
+                echo "Provisioning of the target/cluster is sucessfull!!!"
+            else
+                echo "Provisioning of the target/cluster failed!!! aborting the process"
+                exit 1
+            fi
+        ) "
+    fi
+
     if [ $? == 0 ]
     then
         echo "Provisioning of the target/cluster is sucessfull!!!"
