including docker infra in server manager sanity

diff --git a/testers/smgr_utils b/testers/smgr_utils
--- a/testers/smgr_utils
+++ b/testers/smgr_utils
@@ -829,11 +829,29 @@ function run_smgr_task() {
         reimage_using_SM || debug_and_die "reimage failed"
         provision_using_SM || debug_and_die "provision failed"
     fi
-    add_sourcelist || die "source.list copy failed on all target nodes"
-    install_fabric_cfgm || die "fabric installation failed on cfgm"
-    run_sanity || debug_and_die "Run_sanity step failed"
-    run_tempest || die "Run_Tempest step failed"
-    collect_tech_support || die "Task to collect logs/cores failed"
+    if [[ $TEST_RUN_INFRA == 'docker' ]]; then
+        search_package
+        pkg_file_name=`basename $PKG_FILE`
+        export PACKAGE_VERSION=`echo ${pkg_file_name} | sed 's/contrail-installer-packages[-_]\([0-9\.\-]*\).*/\1/'`
+        if [[ -z $TEST_HOST_STRING ]]; then
+            export TEST_HOST_STRING=$API_SERVER_HOST_STRING
+            export TEST_HOST_PASSWORD=$API_SERVER_HOST_PASSWORD
+        fi
+        export TEST_HOST_IP=`echo $TEST_HOST_STRING | cut -d @ -f2`
+        export TEST_HOST_USER=`echo $TEST_HOST_STRING | cut -d @ -f1`
+        add_sourcelist || die "source.list copy failed on all target nodes"
+        install_fabric_cfgm || die "fabric installation failed on cfgm"
+        setup_testnode || die "test node setup failed"
+        run_sanity_simple || die "run_sanity_simple failed"
+    else
+        install_third_party_pkgs || die "installing GDB/ant failed"
+        run_sanity || die "Run_sanity step failed"
+    fi		
+    #add_sourcelist || die "source.list copy failed on all target nodes"
+    #install_fabric_cfgm || die "fabric installation failed on cfgm"
+    #run_sanity || debug_and_die "Run_sanity step failed"
+    #run_tempest || die "Run_Tempest step failed"
+    #collect_tech_support || die "Task to collect logs/cores failed"
     if [ ${BRANCH} == "R3.0" ]
     then
         delete_pkg_from_SM_cliff_client || die "Task to delete package from SM failed"
