changes to install gdb on all target nodes

diff --git a/testers/smgr_utils b/testers/smgr_utils
--- a/testers/smgr_utils
+++ b/testers/smgr_utils
@@ -4,32 +4,16 @@ TOOLS_WS=${TOOLS_WS:-$(pwd)}
 multi_node=0
 
 #install ant on cfgm0
-#function install_ant() {
+function install_ant() {
+
+    sshpass -p "c0ntrail123" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $API_SERVER_HOST_STRING " (
+        set -x
+        echo "Temporary workaround to installfabric on CFGM"
+        /opt/contrail/contrail_packages/setup.sh
+    ) "
+
+
 function add_sourcelist() {
-    #sshpass -p "c0ntrail123" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $API_SERVER_HOST_STRING " (
-    #    set -x
-    #    echo "Temporary workaround to installfabric on CFGM"
-    #    /opt/contrail/contrail_packages/setup.sh
-    #    cat /etc/apt/sources.list > /etc/apt/sources.list.orig
-    #    cat /etc/apt/sources.list.save > /etc/apt/sources.list
-    #    apt-get update
-    #    apt-get -y --force-yes --allow-unauthenticated install ant
-    #    if [ $? != 0 ]
-    #    then
-    #        echo "failed to install ant on cfgm!!!"
-    #    else
-    #        echo "installed ant successfully"
-    #    fi
-    #    apt-get -y install gdb
-    #    if [ $? != 0 ]
-    #    then
-    #        echo "failed to install gdb on cfgm!!!"
-    #    else
-    #        echo "installed gdb successfully"
-    #    fi
-    #    cat /etc/apt/sources.list > /etc/apt/sources.list.save
-    #    cat /etc/apt/sources.list.orig > /etc/apt/sources.list
-    #) "
 
     HOSTS=`cat "${TOOLS_WS}/testbeds/${tb_filename}" | grep "host[0-9]\s\=" | awk '{print $3}' | awk -F'@' '{print $2}' | tr -d "'"`
     echo $HOSTS
@@ -43,7 +27,20 @@ function add_sourcelist() {
    
             cat /etc/apt/sources.list > /etc/apt/sources.list.orig
             cat /etc/apt/sources.list.save > /etc/apt/sources.list
-            cat /etc/apt/sources.list.save > /etc/apt/testsources.list
+            if [ $? != 0 ]
+                then
+                echo "failed to install ant on cfgm!!!"
+            else
+                echo "installed ant successfully"
+            fi
+            apt-get update
+            apt-get -y install gdb
+            if [ $? != 0 ]
+                then
+                echo "failed to install gdb on cfgm!!!"
+            else
+                echo "installed gdb successfully"
+            fi           
     } "
     sleep 10
     done
@@ -435,8 +432,8 @@ function run_smgr_task() {
     bringup_SM_setup || die "Failed to bringup SM setup" 
     reimage_using_SM || die "reimage failed"
     provision_using_SM || die "provision failed"
-    #install_ant || die "ant installation failed on cfgm"
     add_sourcelist || die "source.list copy failed on all target nodes"
+    install_ant || die "ant installation failed on cfgm"
     run_sanity || die "Run_sanity step failed"
     run_tempest || die "Run_Tempest step failed"
     collect_tech_support || die "Task to collect logs/cores failed"
