Added provision through SM and changes in ceph utils

diff --git a/testers/smgr_utils_ceph b/testers/smgr_utils_ceph
--- a/testers/smgr_utils_ceph
+++ b/testers/smgr_utils_ceph
@@ -339,7 +339,10 @@ function run_smgr_task_ceph() {
     echo "Running tests on $1.."
     search_package_ceph || die "Failed to search packages"
     copy_pkgs_to_sm_fab_node
-    bringup_SM_setup_ceph || die "Failed to bringup SM setup" 
+    if [ $UPGRADE_SM == 1 ]
+    then
+       bringup_SM_setup_ceph || die "Failed to bringup SM setup" 
+    fi
     add_server_and_images_to_SM || die "Failed to bringup SM setup"
     reimage_using_SM_ceph || die "reimage failed"
     provision_using_SM_ceph || die "provision failed"
