Fix for sources.list, ant and cfgm setup.

diff --git a/testers/smgr_ci_utils b/testers/smgr_ci_utils
--- a/testers/smgr_ci_utils
+++ b/testers/smgr_ci_utils
@@ -10,6 +10,7 @@ function install_ant() {
         /opt/contrail/contrail_packages/setup.sh
         cat /etc/apt/sources.list > /etc/apt/sources.list.orig
         cat /etc/apt/sources.list.save > /etc/apt/sources.list
+        sed -i".bak" '/packages.medibuntu.org/d' /etc/apt/sources.list
         apt-get update
         apt-get -y --force-yes --allow-unauthenticated install ant
         if [ $? != 0 ]
@@ -19,9 +20,29 @@ function install_ant() {
             echo "installed ant successfully"
         fi
         apt-get -y install gdb
-        #cat /etc/apt/sources.list > /etc/apt/sources.list.save
-        #cat /etc/apt/sources.list.orig > /etc/apt/sources.list
+        if [ $? != 0 ]
+        then
+            echo "failed to install gdb!!!"
+        else
+            echo "installed gdb successfully"
+        fi
+        if [ $API_SERVER_IP == $word ]; then
+            apt-get -y --force-yes --allow-unauthenticated install ant
+        fi
+        cp /etc/apt/sources.list.orig /etc/apt/sources.list
+        apt-get update
     ) "
+}
+
+function install_fabric_cfgm() {
+
+    sshpass -p "c0ntrail123" ssh root@$SM_SERVER_IP "sshpass -p ${API_SERVER_HOST_PASSWORD} scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null /root/sm_files/contrail_packages/setup.sh ${API_SERVER_HOST_STRING}:/opt/contrail/contrail_packages/"
+    sshpass -p "c0ntrail123" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $API_SERVER_HOST_STRING " (
+        set -x
+        echo "Temporary workaround to installfabric on CFGM"
+        /opt/contrail/contrail_packages/setup.sh
+    ) "
+
 }
 
 
@@ -456,6 +477,7 @@ function run_smgr_task() {
     reimage_using_SM || die "reimage failed"
     provision_using_SM || die "provision failed"
     install_ant || die "ant installation failed on cfgm"
+    install_fabric_cfgm || die "fabric installation failed on cfgm"
     run_ci_sanity || die "Run_sanity step failed"
     run_tempest || die "Run_Tempest step failed"
     collect_tech_support || die "Task to collect logs/cores failed"
