install ant of cfgm nodes

diff --git a/testers/smgr_ci_utils_smlite b/testers/smgr_ci_utils_smlite
--- a/testers/smgr_ci_utils_smlite
+++ b/testers/smgr_ci_utils_smlite
@@ -303,6 +303,7 @@ function run_smgr_task() {
     fi
     export TEST_HOST_IP=`echo $TEST_HOST_STRING | cut -d @ -f2`
     export TEST_HOST_USER=`echo $TEST_HOST_STRING | cut -d @ -f1`
+    install_third_party_pkgs || die "installing GDB/ant failed"
     setup_testnode || die "test node setup failed"
     run_sanity_simple || die "run_sanity_simple failed"
     run_tempest || die "Run_Tempest step failed"
