copying original source list

diff --git a/testers/smgr_utils b/testers/smgr_utils
--- a/testers/smgr_utils
+++ b/testers/smgr_utils
@@ -1,33 +1,54 @@
 #!/usr/bin/env bash
+#!/usr/bin/awk -f
 TOOLS_WS=${TOOLS_WS:-$(pwd)}
 multi_node=0
 
 #install ant on cfgm0
-function install_ant() {
-    sshpass -p "c0ntrail123" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $API_SERVER_HOST_STRING " (
-        set -x
-        echo "Temporary workaround to installfabric on CFGM"
-        /opt/contrail/contrail_packages/setup.sh
-        cat /etc/apt/sources.list > /etc/apt/sources.list.orig
-        cat /etc/apt/sources.list.save > /etc/apt/sources.list
-        apt-get update
-        apt-get -y --force-yes --allow-unauthenticated install ant
-        if [ $? != 0 ]
-        then
-            echo "failed to install ant on cfgm!!!"
-        else
-            echo "installed ant successfully"
-        fi
-        apt-get -y install gdb
-        if [ $? != 0 ]
-        then
-            echo "failed to install gdb on cfgm!!!"
-        else
-            echo "installed gdb successfully"
-        fi
-        cat /etc/apt/sources.list > /etc/apt/sources.list.save
-        cat /etc/apt/sources.list.orig > /etc/apt/sources.list
-    ) "
+#function install_ant() {
+function add_sourcelist() {
+    #sshpass -p "c0ntrail123" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $API_SERVER_HOST_STRING " (
+    #    set -x
+    #    echo "Temporary workaround to installfabric on CFGM"
+    #    /opt/contrail/contrail_packages/setup.sh
+    #    cat /etc/apt/sources.list > /etc/apt/sources.list.orig
+    #    cat /etc/apt/sources.list.save > /etc/apt/sources.list
+    #    apt-get update
+    #    apt-get -y --force-yes --allow-unauthenticated install ant
+    #    if [ $? != 0 ]
+    #    then
+    #        echo "failed to install ant on cfgm!!!"
+    #    else
+    #        echo "installed ant successfully"
+    #    fi
+    #    apt-get -y install gdb
+    #    if [ $? != 0 ]
+    #    then
+    #        echo "failed to install gdb on cfgm!!!"
+    #    else
+    #        echo "installed gdb successfully"
+    #    fi
+    #    cat /etc/apt/sources.list > /etc/apt/sources.list.save
+    #    cat /etc/apt/sources.list.orig > /etc/apt/sources.list
+    #) "
+
+    HOSTS=`cat ${tb_filename} | grep "host[0-9]\s\=" | awk '{print $3}' | awk -F'@' '{print $2}' | tr -d "'"`
+    echo $HOSTS
+    declare -a ARRAY_HOSTS
+    i=0
+    echo $i
+    for word in $HOSTS
+    do
+        echo $word
+        sshpass -p "c0ntrail123" ssh -l root -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $word " {
+   
+            cat /etc/apt/sources.list > /etc/apt/sources.list.orig
+            cat /etc/apt/sources.list.save > /etc/apt/sources.list
+            cat /etc/apt/sources.list.save > /etc/apt/testsources.list
+    } "
+    sleep 10
+    done
+
+
 }
 
 
@@ -414,7 +435,8 @@ function run_smgr_task() {
     bringup_SM_setup || die "Failed to bringup SM setup" 
     reimage_using_SM || die "reimage failed"
     provision_using_SM || die "provision failed"
-    install_ant || die "ant installation failed on cfgm"
+    #install_ant || die "ant installation failed on cfgm"
+    add_sourcelist || die "source.list copy failed on all target nodes"
     run_sanity || die "Run_sanity step failed"
     run_tempest || die "Run_Tempest step failed"
     collect_tech_support || die "Task to collect logs/cores failed"
