including docker for smlite

diff --git a/testers/smgr_ci_utils_smlite b/testers/smgr_ci_utils_smlite
--- a/testers/smgr_ci_utils_smlite
+++ b/testers/smgr_ci_utils_smlite
@@ -294,9 +294,17 @@ function run_smgr_task() {
     reimage_using_SM || debug_and_die "reimage failed"
     copy_smlite_pkg || die "copy of sm-lite packages failed"
     provision_using_SMLite || die "provision failed"
-    add_sourcelist_SMLite || die "source.list copy failed on all target nodes"
-    install_ant || die "ant installation failed on cfgm"
-    run_sanity || die "Run_sanity step failed"
+    search_package
+    pkg_file_name=`basename $PKG_FILE`
+    export PACKAGE_VERSION=`echo ${pkg_file_name} | sed 's/contrail-installer-packages[-_]\([0-9\.\-]*\).*/\1/'`
+    if [[ -z $TEST_HOST_STRING ]]; then
+        export TEST_HOST_STRING=$API_SERVER_HOST_STRING
+        export TEST_HOST_PASSWORD=$API_SERVER_HOST_PASSWORD
+    fi
+    export TEST_HOST_IP=`echo $TEST_HOST_STRING | cut -d @ -f2`
+    export TEST_HOST_USER=`echo $TEST_HOST_STRING | cut -d @ -f1`
+    setup_testnode || die "test node setup failed"
+    run_sanity_simple || die "run_sanity_simple failed"
     run_tempest || die "Run_Tempest step failed"
     collect_tech_support || die "Task to collect logs/cores failed"
     echo "Ending test on $1"
