changes for local packages

diff --git a/testers/utils_ceph b/testers/utils_ceph
--- a/testers/utils_ceph
+++ b/testers/utils_ceph
@@ -9,9 +9,9 @@ function search_package_ceph {
     
     if [ -z $PKG_FILE ]
     then 
-        PKG_FILE=`ls /cs-shared/github-build/${BRANCH}/${BUILDID}/${DISTRO}/${SKU}/contrail-install-packages*` || die "Unable to find install package"
+        PKG_FILE=`ls /github-build/${BRANCH}/${BUILDID}/${DISTRO}/${SKU}/contrail-install-packages*` || die "Unable to find install package"
         export PKG_FILE
-        STORAGE_PKG_FILE=`ls /cs-shared/github-build/${BRANCH}/${BUILDID}/${DISTRO}/${SKU}/artifacts/contrail-storage-packages*~${SKU}_all.deb` || die "Unable to find storage package"
+        STORAGE_PKG_FILE=`ls /github-build/${BRANCH}/${BUILDID}/${DISTRO}/${SKU}/artifacts/contrail-storage-packages*~${SKU}_all.deb` || die "Unable to find install package"
         export STORAGE_PKG_FILE
     else
         pkg_file_name=`basename $PKG_FILE`
@@ -41,9 +41,9 @@ function create_testbed_ceph {
 
     if [ $PKG_LOCAL -eq 1 ]
     then
-       PKG_FILE=$CONTRAIL_LOCAL_PKG_FILE
+       PKG_FILE="${PKG_LOCAL_PATH}/${CONTRAIL_LOCAL_PKG_FILE}"
        export PKG_FILE
-       STORAGE_PKG_FILE=$STORAGE_LOCAL_PKG_FILE
+       STORAGE_PKG_FILE="${PKG_LOCAL_PATH}/${STORAGE_LOCAL_PKG_FILE}"
        export STORAGE_PKG_FILE
     else
         search_package_ceph || die "Unable to locate package"
