storage

diff --git a/testers/utils_ceph b/testers/utils_ceph
--- a/testers/utils_ceph
+++ b/testers/utils_ceph
@@ -188,6 +188,15 @@ function bringup_setup_ceph {
     fab compute_reboot)
 
 }
+
+function bringup_storage {
+ cd ${TOOLS_WS}/contrail-fabric-utils
+ fab install_storage_pkg_all:${PKG_FILE} || die "fab_install_storage_pkg_all failed" 
+ fab install_storage
+ fab setup_storage
+
+}
+
 function reimage_and_bringup_ceph {
     if [ $SKIP_REIMAGE -eq 0 ]
     then
@@ -196,9 +205,13 @@ function reimage_and_bringup_ceph {
     fi
     if [ $SKIP_CONTRAIL_BRINGUP -eq 0 ]
     then
-      bringup_setup_ceph || debug_and_die "Bringup failed!"
+      bringup_setup_ceph || debug_and_die "Bringup contrail failed!"
       sleep 120
       fab restore_repo
+    fi
+    if [ $SKIP_STORAGE_BRINGUP -eq 0]
+    then
+      bringup_storage || debug_and_die "Bringup storage failed!"
     fi
 
     # bring up ceph
