Revert "Match explicitly deb file to avoid matching multiple files with regex"
This reverts commit e1b3db61a18725490a386decd07bf34a0cad8329.

diff --git a/testers/utils b/testers/utils
--- a/testers/utils
+++ b/testers/utils
@@ -12,16 +12,6 @@ function try {
     fi
 }
 
-function get_pkg_suffix_to_use { 
-    pkg_suffix=""
-    if [[ ${DISTRO} =~ ubuntu ]]; then
-        pkg_suffix=".deb"
-    else
-        pkg_suffix=".rpm"
-    fi
-    export pkg_suffix
-}
-
 
 ##
 # search_package
@@ -31,13 +21,12 @@ function search_package {
     if [ -z $PKG_FILE ]
     then 
         mypath=/github-build/${BRANCH}/${BUILDID}/${DISTRO}/${SKU}
-        get_pkg_suffix_to_use
-        if ls ${mypath}/${PKG_FILE_TYPE1}*${pkg_suffix} 1>/dev/null 2>&1; then
-            PKG_FILE=`ls ${mypath}/${PKG_FILE_TYPE1}*${pkg_suffix}` || die "Unable to find install package"
-            PKG_FILE1=`ls ${mypath}/${PKG_FILE_TYPE2}*${pkg_suffix}` || die "Unable to find install package"
+        if ls ${mypath}/${PKG_FILE_TYPE1}* 1>/dev/null 2>&1; then
+            PKG_FILE=`ls ${mypath}/${PKG_FILE_TYPE1}*` || die "Unable to find install package"
+            PKG_FILE1=`ls ${mypath}/${PKG_FILE_TYPE2}*` || die "Unable to find install package"
             export PKG_FILE1
         else
-            PKG_FILE=`ls ${mypath}/${PKG_FILE_TYPE2}*${pkg_suffix}` || die "Unable to find install package"
+            PKG_FILE=`ls ${mypath}/${PKG_FILE_TYPE2}*` || die "Unable to find install package"
             unset PKG_FILE1
         fi
         export PKG_FILE
