Explicit installation of vcenter plugin is not needed from R3.1

diff --git a/testers/utils b/testers/utils
--- a/testers/utils
+++ b/testers/utils
@@ -620,9 +620,12 @@ function setup_and_install_contrail {
         fab compute_reboot
     fi
 
-    if [[ $VCENTER_ONLY_TESTBED -eq 1  || $VCENTER_AS_COMPUTE_TESTBED -eq 1 ]]; then
-        # for vcenter deployments
-        fab install_contrail_vcenter_plugin:${VCENTER_PLUGIN} || die "fab install_contrail_vcenter_plugin failed"
+    #From R3.1.0.0 vcenter plugin will not be posted. The installation is assumed to use plugin from the pkg file
+    if [ "$BRANCH" \< "R3.1" ]; then
+        if [[ $VCENTER_ONLY_TESTBED -eq 1  || $VCENTER_AS_COMPUTE_TESTBED -eq 1 ]]; then
+            # for vcenter deployments
+            fab install_contrail_vcenter_plugin:${VCENTER_PLUGIN} || die "fab install_contrail_vcenter_plugin failed"
+        fi
     fi
 
     if [ $USE_NETWORKING_PKG -eq 1 ]; then
