storage

diff --git a/testers/utils_ceph b/testers/utils_ceph
--- a/testers/utils_ceph
+++ b/testers/utils_ceph
@@ -76,9 +76,10 @@ function create_testbed_ceph {
 
     exec_cmds -s ${TASK_RUNNER_HOST_STRING} -p ${TASK_RUNNER_HOST_PASSWORD} -c "rm -rf $PKG_FILE_DIR/artifacts_extra/"      
     exec_cmds -s ${TASK_RUNNER_HOST_STRING} -p ${TASK_RUNNER_HOST_PASSWORD} -c "mkdir -p $PKG_FILE_DIR/artifacts_extra/"      
+    exec_cmds -s ${TASK_RUNNER_HOST_STRING} -p ${TASK_RUNNER_HOST_PASSWORD} -c "mkdir -p $PKG_FILE_DIR/artifacts/"      
      
-    sshpass -p ${TASK_RUNNER_HOST_PASSWORD} scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $PKG_FILE ${TASK_RUNNER_HOST_STRING}:$PKG_FILE_DIR/
-    sshpass -p ${TASK_RUNNER_HOST_PASSWORD} scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $STORAGE_PKG_FILE ${TASK_RUNNER_HOST_STRING}:$PKG_FILE_DIR/artifacts_extra/
+    sshpass -p ${TASK_RUNNER_HOST_PASSWORD} scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $PKG_FILE ${TASK_RUNNER_HOST_STRING}:$PKG_FILE
+    sshpass -p ${TASK_RUNNER_HOST_PASSWORD} scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $STORAGE_PKG_FILE ${TASK_RUNNER_HOST_STRING}:$STORAGE_PKG_FILE
 
 
 }
@@ -102,7 +103,7 @@ function reimage_setup_ceph {
             fi 
             server-manager reimage --no_confirm --cluster_id $CLUSTER_NAME $REIMAGE_PARAM;
             fab wait_till_all_up:attempts=180,reimaged=True;
-            fab check_reimage_state" || debug_and_die "reimage_setup failed"
+            fab check_reimage_state" || debug_and_die_local "reimage_setup failed"
     fi
 }
 
@@ -115,28 +116,28 @@ function bringup_setup_contrail {
     exec_cmds -s ${TASK_RUNNER_HOST_STRING} -p ${TASK_RUNNER_HOST_PASSWORD} -c "
           cd /tmp/${TBFILE_NAME}/fabric-utils;
           fab install_pkg_all:${PKG_FILE} || die 'fab install_pkg_all:${PKG_FILE} failed'
-          " || debug_and_die "install_pkg_all failed"
+          " || debug_and_die_local "install_pkg_all failed"
 
     if [[ "${DISTRO}" =~ "ubuntu" ]]; then
         exec_cmds -s ${TASK_RUNNER_HOST_STRING} -p ${TASK_RUNNER_HOST_PASSWORD} -c "
           cd /tmp/${TBFILE_NAME}/fabric-utils;
           fab upgrade_kernel_all;
           sleep 60;
-          fab wait_till_all_up:waitdown=False,attempts=30 " || debug_and_die "kernel upgrade/Failed waiting for nodes to come up"
+          fab wait_till_all_up:waitdown=False,attempts=30 " || debug_and_die_local "kernel upgrade/Failed waiting for nodes to come up"
     fi
 
     exec_cmds -s ${TASK_RUNNER_HOST_STRING} -p ${TASK_RUNNER_HOST_PASSWORD} -c "
             cd /tmp/${TBFILE_NAME}/fabric-utils;
             export HA_TEST=$HA_TEST;
             cd fabric-utils;
-            fab install_contrail" || debug_and_die "fab install_contrail failed"
+            fab install_contrail" || debug_and_die_local "fab install_contrail failed"
 
     exec_cmds -s ${TASK_RUNNER_HOST_STRING} -p ${TASK_RUNNER_HOST_PASSWORD} -c "
             cd /tmp/${TBFILE_NAME}/fabric-utils;
             export HA_TEST=$HA_TEST;
             fab setup_interface || exit 1;
             fab add_static_route 
-            fab setup_all" || debug_and_die "fab setup_interface or setup_all task failed"
+            fab setup_all" || debug_and_die_local "fab setup_interface or setup_all task failed"
 }
 
 function bringup_storage {
@@ -144,7 +145,7 @@ function bringup_storage {
             cd /tmp/${TBFILE_NAME}/fabric-utils;
             fab install_storage_pkg_all:${STORAGE_PKG_FILE} || die "fab_install_storage_pkg_all failed" 
             fab install_storage
-            fab setup_storage" || debug_and_die "install_storage_pkg_all failed"
+            fab setup_storage" || debug_and_die_local "install_storage_pkg_all failed"
 
 }
 
@@ -152,19 +153,19 @@ function reimage_and_bringup_ceph {
 
     if [ $SKIP_REIMAGE -eq 0 ]
     then
-      reimage_setup_ceph || debug_and_die "Reimage failed!"
+      reimage_setup_ceph || debug_and_die_local "Reimage failed!"
     fi
 
     update_testbed_file || die "Unable to set the testbed properly for use"
 
     if [ $SKIP_CONTRAIL_BRINGUP -eq 0 ]
     then
-      bringup_setup_contrail || debug_and_die "Bringup contrail failed!"
+      bringup_setup_contrail || debug_and_die_local "Bringup contrail failed!"
     fi
 
     if [ $SKIP_STORAGE_BRINGUP -eq 0 ]
     then
-      bringup_storage || debug_and_die "Bringup storage failed!"
+      bringup_storage || debug_and_die_local "Bringup storage failed!"
     fi
 
     # bring up ceph
@@ -185,6 +186,47 @@ function run_ceph_check {
 
 }
 
+function collect_tech_support_local {
+    if [ $SKIP_LOGS_COLLECTION -ne 0 ]
+    then
+        return 0
+    fi
+
+    NODENAME=`exec_cmds -s ${API_SERVER_HOST_STRING} -p ${API_SERVER_HOST_PASSWORD} -c  "hostname -s"`
+    NODENAME=`echo $NODENAME | sed 's/\\r//g'`
+    dest_dir_folder=$DEBUG_LOG_DIR/${NODENAME}/${SCRIPT_TIMESTAMP}
+    debug_cmds="export HA_TEST=$HA_TEST && fab attach_logs_cores:$DEBUG_LOG_DIR/${NODENAME},${SCRIPT_TIMESTAMP} ; $cp_log_cmd ; cp fabfile/testbeds/testbed.py $dest_dir_folder ;  cp *.log $dest_dir_folder"
+          
+    exec_cmds -s ${TASK_RUNNER_HOST_STRING} -p ${TASK_RUNNER_HOST_PASSWORD} -c "
+            cd /tmp/$TBFILE_NAME/fabric-utils;
+            $debug_cmds"
+}
+
+
+function debug_and_die_local
+{
+    local message=$1
+    if [ $LOCK_TESTBED_ON_FAILURE = 1 ]; then
+        echo "Testbed is set to be locked on failure"
+        if [[ $message =~ 'Test failures exceed' ]]; then
+            collect_tech_support_local
+        fi
+        export RELEASE_TESTBED=0
+        (  
+            set -x
+            flock 5
+            echo "Locking testbed $tb_lock_file for debugging"
+            echo "Testbed locked..Unlock when debug complete" >> $tb_lock_file
+            cat $tb_lock_file
+        ) 5>${LOCK_FILE_DIR}/lockfile
+    else
+        collect_tech_support_local
+    fi
+    [ -z "$message" ] && message="Died"
+    echo "${BASH_SOURCE[1]}: line ${BASH_LINENO[0]}: ${FUNCNAME[1]}: $message." >&2
+    cat $tb_lock_file
+    exit 1
+}
 function run_ceph_fab_sanity() {
     echo "Running tests on $TBFILE_NAME .." 
     create_testbed_ceph
@@ -192,6 +234,6 @@ function run_ceph_fab_sanity() {
     run_ceph_check || die "run_ceph_check step failed"
     #run_tempest || die "Run_Tempest step failed"
     echo "Test Done" 
-    #collect_tech_support || die "Task to collect logs/cores failed"
+    collect_tech_support_local || die "Task to collect logs/cores failed"
     echo "Ending test on $TBFILE_NAME"
 }
