storage

diff --git a/testers/utils_ceph b/testers/utils_ceph
--- a/testers/utils_ceph
+++ b/testers/utils_ceph
@@ -236,11 +236,24 @@ function run_sanity {
 }
 
 
+function run_ceph_check {
+  result=`exec_cmds -s ${TASK_RUNNER_HOST_STRING} -p ${TASK_RUNNER_HOST_PASSWORD} -c  "/root/sm_files/check_ceph_status.py $CLUSTER_NAME $OSD_COUNT"`
+  echo $result | grep "CEPH_STATUS_CHECK_OK"
+  return_val=`echo $?`
+
+  if [[ $return_val != 0 ]]
+  then
+    die "CEPH_STATUS_CHECK : FAILED"
+  else
+    echo "CEPH_STATUS_CHECK : PASS"
+  fi
+}
+
 function run_ceph_fab_sanity() {
     create_testbed_ceph || die "Failed to create required testbed details"
     echo "Running tests on $TBFILE_NAME .." 
     reimage_and_bringup_ceph
-    #run_sanity_ceph || die "Run_sanity step failed"
+    run_ceph_check || die "run_ceph_check step failed"
     #run_tempest || die "Run_Tempest step failed"
     echo "Test Done" 
     collect_tech_support || die "Task to collect logs/cores failed"
