updating upstream source.list and removing explicit installation of ANT package

diff --git a/testers/utils b/testers/utils
--- a/testers/utils
+++ b/testers/utils
@@ -26,31 +26,34 @@ function get_pkg_suffix_to_use {
 }
 
 #install ant on cfgm0
-function install_ant() {
+function add_sourcelist() {
+
+    if [ $SKIP_SOURCELIST -ne 0 ]
+    then
+        return 0
+    fi
+
     if [[ ${DISTRO} =~ ubuntu ]]; then
 
-        sshpass -p "c0ntrail123" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $API_SERVER_HOST_STRING " (
-            set -x
-            cat /etc/apt/sources.list > /etc/apt/sources.list.orig
-            cat /etc/apt/sources.list.save > /etc/apt/sources.list
-            apt-get update
-            apt-get -y --force-yes --allow-unauthenticated install ant
-            if [ $? != 0 ]
-            then
-                echo "failed to install ant on cfgm!!!"
-            else
-                echo "installed ant successfully"
-            fi
-            apt-get -y install gdb
-            if [ $? != 0 ]
-            then
-                echo "failed to install gdb on cfgm!!!"
-            else
-                echo "installed gdb successfully"
-            fi
-            cat /etc/apt/sources.list > /etc/apt/sources.list.save
-            cat /etc/apt/sources.list.orig > /etc/apt/sources.list
-        ) "
+        HOSTS=`cat "${TOOLS_WS}/testbeds/${tb_filename}" | grep "host[0-9]\s\=" | awk '{print $3}' | awk -F'@' '{print $2}' | tr -d "'"`
+        echo $HOSTS
+        for word in $HOSTS
+        do
+            echo $word
+            sshpass -p "c0ntrail123" ssh -l root -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $word " {
+   
+                cat /etc/apt/sources.list > /etc/apt/sources.list.orig
+                cat /etc/apt/sources.list.save > /etc/apt/sources.list
+                if [ $? != 0 ]
+                then
+                    echo "failed to copy upstream source list!!!"
+                else
+                    echo "Copy of upstream source list is sucessfull"
+                fi
+                apt-get update
+
+            } "
+        done
     fi
 }
 
@@ -841,7 +844,7 @@ function run_task() {
     create_testbed || die "Failed to create required testbed details"
     echo "Running tests on $TBFILE_NAME .." 
     reimage_and_bringup
-    install_ant || die "ant installation failed on cfgm" 
+    add_sourcelist || die "copy of upstream source list failed" 
     #bringup_setup || die "Bringup failed"
     run_sanity || die "Run_sanity step failed"
     run_tempest || die "Run_Tempest step failed"
