Revert "Adapt to new packaging scheme of installer packages"
This reverts commit d2934aa596ee7bb86648bb0a12c7eb2b8076eaf0.

diff --git a/testers/utils b/testers/utils
--- a/testers/utils
+++ b/testers/utils
@@ -16,22 +16,11 @@ function try {
 ##
 # search_package
 function search_package {
-    PKG_FILE_TYPE1="contrail-installer-package"
-    PKG_FILE_TYPE2="contrail-install-packages"
     if [ -z $PKG_FILE ]
     then 
-        mypath=/github-build/${BRANCH}/${BUILDID}/${DISTRO}/${SKU}
-        if ls ${mypath}/${PKG_FILE_TYPE1}* 1>/dev/null 2>&1; then
-            PKG_FILE=`ls ${mypath}/${PKG_FILE_TYPE1}*` || die "Unable to find install package"
-            PKG_FILE1=`ls ${mypath}/${PKG_FILE_TYPE2}*` || die "Unable to find install package"
-            export PKG_FILE1
-        else
-            PKG_FILE=`ls ${mypath}/${PKG_FILE_TYPE2}*` || die "Unable to find install package"
-            unset PKG_FILE1
-        fi
+        PKG_FILE=`ls /github-build/${BRANCH}/${BUILDID}/${DISTRO}/${SKU}/contrail-install-packages*` || die "Unable to find install package"
         export PKG_FILE
     else
-        # !!!! DO NOT SET PKG_FILE directly as of now !!!!
         pkg_file_name=`basename $PKG_FILE`
         re_ubuntu="contrail-install-packages_(.*)-(.*)~.*(.deb)"
         re_centos="contrail-install-packages-(.*)-(.*)~.*(.rpm)"
@@ -257,15 +246,7 @@ function use_testbed_file {
 
 function run_setup_shell_script {
     exec_cmds -s ${API_SERVER_HOST_STRING} -p ${API_SERVER_HOST_PASSWORD} -c "
-        if [ -d /opt/contrail/contrail_installer_package ]; then
-            bash -x /opt/contrail/contrail_installer_package/setup.sh;
-        fi
-        if [ -f /opt/contrail/contrail_install_packages/setup.sh ]; then
-            bash -x /opt/contrail/contrail_install_packages/setup.sh;
-        fi
-        if [ -f /opt/contrail/contrail_packages/setup.sh ]; then
-            bash -x /opt/contrail/contrail_packages/setup.sh;
-        fi "  || debug_and_die "Failed while running setup.sh" 
+        find /opt/contrail -name "setup.sh" -exec {} \;"  || debug_and_die "Failed while running setup.sh"
 }
 
 # bringup_setup
@@ -282,9 +263,6 @@ function bringup_setup {
     fab prov_esxi
     sleep 60
     fab install_pkg_all:${PKG_FILE} || die "fab install_pkg_all:${PKG_FILE} failed"
-    if [ -n "$PKG_FILE1" ]; then
-        fab install_pkg_all:${PKG_FILE1} || die "fab install_pkg_all:${PKG_FILE1} failed"
-    fi
     run_setup_shell_script
 
     # Upgrade biosdevname if ubuntu-14-04
