Until Bug 1387838 is fixed, use sleep

diff --git a/testers/utils b/testers/utils
--- a/testers/utils
+++ b/testers/utils
@@ -259,7 +259,9 @@ function bringup_setup {
     cd ${TOOLS_WS}/contrail-fabric-utils
     if [[ ${DISTRO} =~ ubuntu ]]; then
         fab upgrade_kernel_all || die "Upgrading Kernel failed"
-        fab wait_till_all_up:attempts=30 || die "Failed waiting for nodes to come up"
+        # Until 1387838 is fixed, use sleep
+#        fab wait_till_all_up:attempts=30 || die "Failed waiting for nodes to come up"
+        sleep 600
     fi
 
     # install contrail packages on all node
@@ -325,13 +327,16 @@ function reimage_setup {
         exec_cmds -s ${SVL_HOST_STRING} -p ${SVL_HOST_PASSWORD} -c "
             cd /tmp/$TBFILE_NAME/contrail-fabric-utils;
             fab all_sm_reimage:$REIMAGE_PARAM ;
-            fab wait_till_all_up:attempts=120;
+            #fab wait_till_all_up:attempts=120;
+            sleep 1200;
             fab check_reimage_state"
     else
         cd ${TOOLS_WS}/contrail-fabric-utils
         # server-manager reimage
         fab all_sm_reimage:$REIMAGE_PARAM
-        fab wait_till_all_up:attempts=120
+        # Until 1387838 is fixed, use sleep
+#        fab wait_till_all_up:attempts=120
+        sleep 1200
         # verify reimage is successful or failure
         fab check_reimage_state
     fi
