disabled ceph status check so that it can be checked by storage scripts case by case.

diff --git a/testers/utils_ceph b/testers/utils_ceph
--- a/testers/utils_ceph
+++ b/testers/utils_ceph
@@ -347,7 +347,7 @@ function run_ceph_fab_sanity() {
     create_testbed_ceph
     reimage_and_bringup_ceph
     copy_tbfile_to_api_server
-    run_ceph_check || die "run_ceph_check step failed"
+    #run_ceph_check || die "run_ceph_check step failed"
     echo "Test Done" 
     collect_tech_support_local || die "Task to collect logs/cores failed"
     echo "Ending test on $TBFILE_NAME"
