Support sanity with docker
This patch is to supprot running sanity with contrail-test docker
container.

diff --git a/testers/utils b/testers/utils
--- a/testers/utils
+++ b/testers/utils
@@ -295,7 +295,18 @@ function copy_bgp_stress_test_binary {
         return 0
     fi
 #    search_package
-    exec_cmds -s ${TASK_RUNNER_HOST_STRING} -p ${TASK_RUNNER_HOST_PASSWORD} -c "sshpass -p $API_SERVER_HOST_PASSWORD scp $PKG_FILE_DIR/store/sandbox/build/debug/bgp/test/bgp_stress_test ${API_SERVER_HOST_STRING}:$CFGM_TEST_CODE_PATH" || die "Failed to copy the bgp_stress_test binary  to $API_SERVER_HOST_STRING:"
+    exec_cmds -s ${TASK_RUNNER_HOST_STRING} -p ${TASK_RUNNER_HOST_PASSWORD} -c "sshpass -p $TEST_HOST_PASSWORD scp $PKG_FILE_DIR/store/sandbox/build/debug/bgp/test/bgp_stress_test ${TEST_HOST_STRING}:$CFGM_TEST_CODE_PATH" || die "Failed to copy the bgp_stress_test binary  to $TEST_HOST_STRING:"
+}
+
+# checkout_repo
+function checkout_fab_repo {
+    cd $TOOLS_WS
+    git clone git@github.com:Juniper/contrail-fabric-utils.git
+    ( cd $TOOLS_WS/contrail-fabric-utils
+      git stash
+      git checkout -b ${FAB_GIT_BRANCH} origin/${FAB_GIT_BRANCH}
+      git pull
+    )
 }
 
 ##
@@ -624,8 +635,20 @@ function add_to_sources_list {
        sshpass -p ${API_SERVER_HOST_PASSWORD} ssh -t -t ${SSHOPT} $API_SERVER_HOST_STRING ' (
        cd /etc/apt/; cp sources.list sources.list.original; echo 'deb http://us.archive.ubuntu.com/ubuntu trusty main' >> sources.list; apt-get update;
        echo "sources.list modified" )'
-       fi
+   fi
 }
+
+function run_sanity_simple {
+    if [ $SKIP_SANITY -ne 0 ]; then
+        return 0
+    fi
+    search_package
+    setup_sanity_base_simple
+    if [[ "$TEST_RUN_CMD" != *"-d"* ]]; then
+        stop_on_failure
+    fi
+}
+
 # run_sanity serial/parallel
 function run_sanity {
     if [ $SKIP_SANITY -ne 0 ]
@@ -693,7 +716,75 @@ function set_threshold {
 
 }
 
-# base setup for sanity 
+function setup_testnode {
+    if [[ $DISTRO =~ 'ubuntu' ]]; then
+        container_image_path=${TEST_CONTAINER_IMAGE:-"${TEST_CONTAINER_IMAGE_DIR}/docker-image-${TEST_RUN}-${SKU}-${PACKAGE_VERSION}.tar.gz"}
+        container_image_file=`basename $container_image_path`
+        if [[ ! -f $container_image_path ]]; then
+            echo "ERROR!! Container image $container_image_path doesnt exist"
+            exit 1
+        fi
+        sshpass -p $TEST_HOST_PASSWORD scp $container_image_path $TEST_HOST_STRING:/tmp/
+        exec_cmds -s $TEST_HOST_STRING -p $TEST_HOST_PASSWORD -c "(
+            docker  -v &> /dev/null ; rv=$?
+            if [ \$rv -ne 0 ]; then
+              DEBIAN_FRONTEND=noninteractive
+              apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D && \
+              echo 'deb https://apt.dockerproject.org/repo ubuntu-trusty main'  > /etc/apt/sources.list.d/docker.list && \
+              echo 'deb http://cz.archive.ubuntu.com/ubuntu trusty main'  > /etc/apt/sources.list.d/ubuntu-archive.list && \
+              apt-get -y update; apt-get install -y --force-yes docker-engine ;\
+	        fi
+	        s=$(docker images -q ${TEST_RUN}-${SKU}:${PACKAGE_VERSION} | grep -c [a-z])
+            wget -O /usr/local/bin/testrunner.sh https://raw.githubusercontent.com/Juniper/contrail-test-ci/master/testrunner.sh
+            chmod +x /usr/local/bin/testrunner.sh
+            if [ \$s -eq 0 ]; then
+	            testrunner load < /tmp/${container_image_file}
+            fi
+            mkdir -p ${HOME}/contrail-test-runs/${SCRIPT_TIMESTAMP}
+	    )"
+            sshpass -p $TEST_HOST_PASSWORD scp ${TOOLS_WS}/testbeds/${tb_filename} $TEST_HOST_STRING:${HOME}/contrail-test-runs/${SCRIPT_TIMESTAMP}/testbed.py
+    else
+      echo "Only ubuntu is supported for test node at this moment"
+    fi
+}
+
+function setup_sanity_base_simple {
+    jenkins_triggered=${JENKINS_TRIGGERED:-0}
+
+    # run sanity in parallel/serial branch, default serial
+    if [ "${sanitytype}" = "" ]; then
+        sanitytype="serial"
+    fi
+
+    #PARAMS_FILE=$CFGM_TEST_CODE_PATH/scripts/sanity_params.ini
+    #TEST_CONFIG_FILE=$CFGM_TEST_CODE_PATH/sanity_params.ini
+    if [[ "$TEST_RUN_CMD" == *"control_node_scaling"* ]]; then
+        copy_bgp_stress_test_binary # This is not going to work in container, this will need to happen while building the container
+    fi
+    sanity_cmd="bash -x /usr/local/bin/testrunner.sh run -t ${HOME}/contrail-test-runs/${SCRIPT_TIMESTAMP}/testbed.py ${TEST_RUN}-${SKU}:${PACKAGE_VERSION}"
+    if [ $PARALLEL_RUN -eq 1 ]; then
+         $EXTRA_RUN_TEST_ARGS="$EXTRA_RUN_TEST_ARGS -t "
+    fi
+    pythonpath=""
+
+    exec_cmds -s ${TEST_HOST_STRING} -p ${TEST_HOST_PASSWORD} -c "export CT_SCRIPT_TS=${SCRIPT_TIMESTAMP};
+                                                         export CT_TEST_RUN_CMD=${TEST_RUN_CMD};
+                                                         export CT_EXTRA_RUN_TEST_ARGS=${EXTRA_RUN_TEST_ARGS};
+                                                         export CT_JENKINS_TRIGGERED=${jenkins_triggered};
+                                                         export CT_BUILD_ID=${BUILDID};
+                                                         export CT_PARAMS_FILE=${PARAMS_FILE};
+                                                         export CT_TEST_TYPE=${TEST_TYPE};
+                                                         export CT_EMAIL_SUBJECT_PREFIX=\"${EMAIL_SUBJECT_PREFIX}\";
+                                                         export CT_EMAIL_SUBJECT=\"${EMAIL_SUBJECT}\";
+                                                         export CT_MX_GW_TEST=${MX_GW_TEST};
+                                                         export CT_IMAGE_WEB_SERVER=${IMAGE_WEB_SERVER};
+                                                         export CT_BRANCH=$BRANCH;
+                                                         $OTHER_OPTS
+                                                         $pythonpath
+                                                         ${sanity_cmd};" || die "Task to run sanity failed"
+}
+
+# base setup for sanity
 function setup_sanity_base {
     jenkins_triggered=${JENKINS_TRIGGERED:-0}
     OTHER_OPTS=""
@@ -863,12 +954,15 @@ function reimage_and_bringup {
 function create_testbed {
 
     search_package || die "Unable to locate package"
-
     if [ "$BRANCH" = "R1.10" ]; then
         export NEW_TEST_INFRA=0
     fi
-
-    checkout_repo || die "Unable to checkout fab/test repos"
+    if [[ $TEST_RUN_INFRA == 'docker' ]]; then
+        # No need to fetch test repos in case of docker
+        checkout_fab_repo || die "Unable to checkout fab/test repos" # No need to checkout test repo for container
+    else
+        checkout_repo
+    fi
     use_testbed_file || die "Unable to set the testbed properly for use"
     be_ready_to_reimage_remotely || die "Unable to setup the system for reimaging in US"
 }
@@ -950,13 +1044,20 @@ function unlock_testbed() {
 
 function run_task() {
     create_testbed || die "Failed to create required testbed details"
-    echo "Running tests on $TBFILE_NAME .." 
+    echo "Running tests on $TBFILE_NAME .."
     reimage_and_bringup
-    install_third_party_pkgs || die "installing GDB/ant failed" 
-    #bringup_setup || die "Bringup failed"
-    run_sanity || die "Run_sanity step failed"
+    if [[ $TEST_RUN_INFRA == 'docker' ]]; then
+        search_package
+        pkg_file_name=`basename $PKG_FILE`
+        export PACKAGE_VERSION=`echo ${pkg_file_name} | sed 's/contrail-install-packages_\([0-9\.\-]*\).*/\1/'`
+        setup_testnode || die "test node setup failed"
+        run_sanity_simple || die "run_sanity_simple failed"
+    else
+        install_third_party_pkgs || die "installing GDB/ant failed"
+        run_sanity || die "Run_sanity step failed"
+    fi
     run_tempest || die "Run_Tempest step failed"
-    echo "Test Done" 
+    echo "Test Done"
     collect_tech_support || die "Task to collect logs/cores failed"
     echo "Ending test on $TBFILE_NAME"
 }
